theme: jekyll-theme-minimal
title: Sunny K Gupta
description: This is my homepage which is under construction.
position: Undergraduate student
affiliation: Indian Institute of Science Education and Research (IISER) Bhopal
email: sunny20 (at) iiserb (dot) ac (dot) in
github_link: https://github.com/sygbyte
linkedin: https://www.linkedin.com/in/sygbyte
twitter: https://twitter.com/sygupta
